version: '3'

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: mix phx.server
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: nfl_rushing_dev
      PGHOST: db
      PGPORT: 5432
      MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - web:/opt/app
  db:
    image: postgres:9.6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  web:
